apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: {{ .Release.Namespace }}
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: nginx:1.21.6-alpine
        imagePullPolicy: IfNotPresent
        command: ["tail"]
        args: ["-f", "/dev/null"]
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "4Gi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: hello-world
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: {{ .Values.nodeport }}
      port: 80
      targetPort: 80
      name: web