apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: {{ .Release.Namespace }}
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: nginx:1.21.6-alpine
        imagePullPolicy: IfNotPresent
        command: ["nginx"]
        args: ["-g", "daemon off;"]
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "4Gi"
            cpu: "250m"
        volumeMounts:
        - name: nginx-conf-mount
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-conf-mount
        configMap:
          name: nginx-conf

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: |
    events { }
    http {
        client_max_body_size 2M;
        # To test the nginx location priority, you can use the following test website
        # https://nginx.viraptor.info/
        server {
            listen 80;
            proxy_http_version 1.1; # Add me for Envoy compatibility!
            # endpoint for health check;
            location = / {
                return 200 "Hello";
            }
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: hello-world
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: {{ .Values.nodeport }}
      port: 80
      targetPort: 80
      name: web